---


- name: "SECTION | 4.2 | Configure Logging"
  ansible.builtin.import_tasks:
      file: cis_4.2.1.x.yml
  when: rhel9cis_syslog == 'rsyslog'

- name: "SECTION | 4.2.2 | Configure journald"
  ansible.builtin.import_tasks:
      file: cis_4.2.2.x.yml
  when: rhel9cis_syslog == 'journald'

- name: "SECTION | 4.2.3 | Configure logile perms"
  ansible.builtin.import_tasks:
      file: cis_4.2.3.yml

- name: "SECTION | 4.3 | Configure logrotate"
  ansible.builtin.import_tasks:
      file: cis_4.3.yml
